const messages = {
    messages: [{
            firstname: "bbbbbbbbbbbbbbbbbbb",
            lastname: "bbbbbbbbbbbbbbbbbbbbb",
            avis: "bbbbbbbbbbbbbbbbbb bbbbbbbbbbbbbbbbb bbbbb bbb bbbbbbbbbbbbbbbbbbbbbbbbbb bbbbbbbbbbbbbbbbbbbbbbbb bbbbbbbbbbbbbb bbbb",
            note: "2",
            formation: "Backend",
            date: "Sat Jul 30 2022 06:08:59 GMT+0300 (heure normale d’Afrique de l’Est)",
        },
        {
            firstname: "eeeeeeeeeeeee",
            lastname: "eeeeeeeeeeeeeeeeeeee",
            avis: "eeeeeeeeeeeeeeeeee",
            note: "5",
            formation: "UXUI",
            date: "Sat Jul 30 2022 06:46:28 GMT+0300 (heure normale d’Afrique de l’Est)",
        },
        {
            firstname: "fffffffffffff",
            lastname: "fffffffffffffffffff",
            avis: "fffffffffffffffffff ff f ff fffezrrrrrzerzfffffffff  f fferzeeeeeeeeeeeeezer f f fffffffff ffffffff ffffff f f f ffffzerrrrrrrrrrrrzrefffffffffffff ffrezrazraff",
            note: "1",
            formation: "Backend",
            date: "Sat Jul 30 2022 06:54:05 GMT+0300 (heure normale d’Afrique de l’Est)",
        },
        {
            firstname: "hhhhhhhhhhhhhhhh",
            lastname: "hhhhhhhhhhhhhhhhhh",
            avis: "hhhhhhhhhhhhhhh",
            note: "3",
            formation: "Frontend",
            date: "Sat Jul 30 2022 06:55:32 GMT+0300 (heure normale d’Afrique de l’Est)",
        },
        {
            firstname: "iiiiiiiiiiiiiiiiiiiiiiiii",
            lastname: "iiiiiiiiiiiiiiiiiiiiiii",
            avis: "iiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
            note: "1",
            formation: "Backend",
            date: "Sat Jul 30 2022 09:26:43 GMT+0300 (heure normale d’Afrique de l’Est)",
        },
        {
            firstname: "iiiiiiiiiiiiiiiiiiiiiiiii",
            lastname: "iiiiiiiiiiiiiiiiiiiiiii",
            avis: "iiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
            note: "1",
            formation: "Backend",
            date: "Sat Jul 30 2022 09:32:22 GMT+0300 (heure normale d’Afrique de l’Est)",
        },
        {
            firstname: "kkkkkkkkkkkk",
            lastname: "kkkkkkkkkkkkkk",
            avis: "kkkkkkkkkkkkkkk kk kk kkkkkkkkkkkkkkkkkkkkkkkkkkkkk k kk k kk kkk kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk kkkkkkkkkkkkkkkkkk k  kk k kkkkkkkkkkkkkkkkkkk",
            note: "5",
            formation: "Backend",
            date: "Sat Jul 30 2022 09:34:58 GMT+0300 (heure normale d’Afrique de l’Est)",
        },
        {
            firstname: "lllllllllllllllllllllllllllll",
            lastname: "llllllllllllllllllllll",
            avis: "lllllllllllllllllllllll",
            note: "1",
            formation: "Marketing",
            date: "Sat Jul 30 2022 10:23:33 GMT+0300 (heure normale d’Afrique de l’Est)",
        },
        {
            firstname: "mmmmmmmmmmmm",
            lastname: "mmmmmmmmmmmmmmmm",
            avis: "mmmmmmmmmmmmmm",
            note: "2",
            formation: "Marketing",
            date: "Sat Jul 30 2022 10:28:19 GMT+0300 (heure normale d’Afrique de l’Est)",
        },
        {
            firstname: "eazd",
            lastname: "aear",
            avis: "ae",
            note: "2",
            formation: "Frontend",
            date: "Sat Jul 30 2022 11:48:11 GMT+0300 (heure normale d’Afrique de l’Est)",
        },
        {
            firstname: "nnnnnnnnnnnnn",
            lastname: "nnnnnnnnnnnnnnn",
            avis: "nnnnnnnnnnnnnnnnn",
            note: "3",
            formation: "Backend",
            date: "Sat Jul 30 2022 11:50:01 GMT+0300 (heure normale d’Afrique de l’Est)",
        },
        {
            firstname: "etzt",
            lastname: "zetzet",
            avis: "zetzet",
            note: "3",
            formation: "Frontend",
            date: "Sat Jul 30 2022 12:17:07 GMT+0300 (heure normale d’Afrique de l’Est)",
        },
        {
            firstname: "oooooooooooooooooooo",
            lastname: "OOOOOOOOOOOOOO",
            avis: "OOOOOOOOOOOOOOOOOOOO",
            note: "4",
            formation: "Frontend",
            date: "Sat Jul 30 2022 16:58:01 GMT+0300 (heure normale d’Afrique de l’Est)",
        },
        {
            firstname: "PPPPPPPPPPPP",
            lastname: "pppppppppppppppppppp ppppppppppppppppppppp",
            avis: "Pp pppPpPPP PP Ppp pp p ppP P pp P Pp , ppp pP PP ! ppppp pP P pPPPPPPPPPPP  pP Pp         ppppppppp pp p p p p p p  :)",
            note: "4",
            formation: "Marketing",
            date: "Sat Jul 30 2022 09:11:35 GMT+0300 (heure normale d’Afrique de l’Est)",
        },
        {
            firstname: "PPPPPPPPPPPP",
            lastname: "pppppppppppppppppppp ppppppppppppppppppppp",
            avis: "Pp pppPpPPP PP Ppp pp p ppP P pp P Pp , ppp pP PP ! ppppp pP P pPPPPPPPPPPP  pP Pp         ppppppppp pp p p p p p p  :)",
            note: "4",
            formation: "Marketing",
            date: "Sat Jul 30 2022 09:13:03 GMT+0300 (heure normale d’Afrique de l’Est)",
        },
        {
            firstname: "Toky",
            lastname: "Rab",
            avis: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Recusandae animi reiciendis provident blanditiis dolores ad et dolorem quas, cumque excepturi, nostrum sequi? Nobis doloremque, eum iste nisi nostrum, dolorem iusto sequi beatae blanditiis eaque totam ut sed. Modi doloremque molestias id, aut dolores illo, accusamus saepe eligendi sed iusto beatae!",
            note: "5",
            formation: "UXUI",
            date: "Sat Jul 30 2022 09:24:47 GMT+0300 (heure normale d’Afrique de l’Est)",
        },
        {
            firstname: "zefrzer",
            lastname: "zerzerzerzer",
            avis: "zerzer",
            note: "1",
            formation: "Backend",
            date: "Sat Jul 30 2022 09:28:14 GMT+0300 (heure normale d’Afrique de l’Est)",
        },
    ],
};
module.exports = messages;